title: Amir Muhsin
email: mirmuhsin.sodiqov@gmail.com
description: Android/Game Developer
baseurl: ""
url: "https://amirmuhsin.github.io"
github_username: amirmuhsin

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
permalink: /:year/:month/:day/:title.html
